import { pokemon } from "./pokemon";

export const POKEMONS: pokemon[] = [{
    id:1,
    name:"bilbizare",
    hp:25,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["plantes","poisson"],
    created:new Date()
},
{
    id:2,
    name:"salameche",
    hp:10,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["feu"],
    created:new Date(),
},
{
    id:3,
    name:"carapace",
    hp:25,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["eau"],
    created:new Date(),
},
{
    id:4,
    name:"etienne",
    hp:1,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["herbes","viande"],
    created:new Date(),
},
{
    id:5,
    name:"sore",
    hp:35,
    cp:1,
    picture:"./assets.img6.jpg",
    types:["humains"],
    created:new Date(),
},
{
    id:6,
    name:"hentol",
    hp:25,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["plantes","poisson"],
    created:new Date(),
},
{
    id:7,
    name:"spek",
    hp:15,
    cp:3,
    picture:"./assets.img6.jpg",
    types:["fruits","arachide"],
    created:new Date(),
},
{
    id:8,
    name:"vige",
    hp:3,
    cp:3,
    picture:"./assets.img6.jpg",
    types:["plantes","poisson"],
    created:new Date(),
},
{
    id:9,
    name:"anthol",
    hp:75,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["sable"],
    created:new Date(),
},
{
    id:10,
    name:"rosignor",
    hp:25,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["tomate"],
    created:new Date(),
},
{
    id:11,
    name:"salin",
    hp:25,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["plantes","poisson"],
    created:new Date(),
},
{
    id:12,
    name:"rouvain",
    hp:25,
    cp:5,
    picture:"./assets.img6.jpg",
    types:["pommes","feu"],
    created:new Date(),
},
]